services:
  # db2:
  #   image: icr.io/db2/db2-community:latest
  #   container_name: db2_blotter
  #   environment:
  #     LICENSE: accept
  #     DB2INST1_PASSWORD: Blotter2025
  #     DBNAME: db_blotter
  #     ARCHIVE_LOGS: "false"
  #     ENABLE_ORACLE_COMPATIBILITY: "false"
  #   ports:
  #     - "61000:50000"
  #   volumes:
  #     - db2_data:/database
  #   restart: unless-stopped

  api:
    build: ./app
    container_name: nestjs_api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres_blotter
    environment:
      POSTGRES_USER: blotter
      POSTGRES_PASSWORD: Blotter2025
      POSTGRES_DB: db_blotter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init/:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  was:
    build: ./was-liberty
    container_name: liberty_server
    depends_on:
      - postgres
    ports:
      - "9080:9080"
    volumes:
      - was_config:/config
    restart: unless-stopped

volumes:
  # db2_data:
  postgres_data:
  was_config:
